version: "3.3"
services:
  influxdb:
      image: influxdb:latest
      ports:
        - '8086:8086'
      volumes:
        - influxdb-storage:/var/lib/influxdb
      environment:
        - INFLUXDB_DB=db0
        - INFLUXDB_ADMIN_USER=test
        - INFLUXDB_ADMIN_PASSWORD=test
        #- INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
        #- INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  web:
    build: .
    volumes: 
        - .:/app
    ports:
      - "5000:5000"
    #volumes:
      #- .:/app
    depends_on:
      - influxdb
    environment: 
      PORT: 5000
      FLASK_DEBUG: 1
      influxdbhost: "192.168.103.111"
      influxdbport: "8086"
      influxdbusername: "test"
      influxdbpass: "test"
      influxdbdatabase: "HomeStatus"

volumes:
  influxdb-storage:
